[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
tokio = "1.45.1"
serde = { version = "1.0.219", features = ["derive"] }
serde-xml-rs = "0.6.0"
lazy_static = "1.5.0"